### ISSUE TITLE
push to testnet.zap.me

### ISSUE THREAD

**Issue by djpnewton** [djpnewton/zapd#16]
- Update test instance with new "initialize wallet table" button
- Initialize wallet table

**Comment by eoliveros** [comment]
need confirmation on the ansible_script.sh, i think i should run:

ansible_script.sh test no_keys

can you confirm?

**Comment by djpnewton** [comment]
yes

for the problem with too many forward slashes update the url heres: 

 - https://github.com/zap-me/zapd/blob/5d256775190031711fe3837ff2064dd6859da06d/zapd/utils.py#L126
 - https://github.com/zap-me/zapd/blob/5d256775190031711fe3837ff2064dd6859da06d/zapd/utils.py#L137

because there are other places that use the base node url.

create a PR with those updates can we can test again

**Comment by eoliveros** [comment]
When I was initially running it, it opens up the page but fails to initialise when i press the button.
The address has an extra "/" and that causes it to fail. To get it to initialise, i deleted the the "/" at the end of the node_http_base_url inside the config.cfg then restart. Click initialise that worked. Place the "/" back afterwards.


So basically, this is going to fail if deployed in prod.

thinking of doing some thing like this in the models.py

currently:
```
node = cfg.node_http_base_url
```

changing to:
```
node = cfg.node_http_base_url[:-1]
```

will do some test to see if this will work in my env.

**Comment by eoliveros** [comment]
worked on my env.
![image](https://user-images.githubusercontent.com/47799652/84717243-666e1880-afc9-11ea-9bee-134a10b88348.png)

with this config.cfg:
```
node_http_base_url=http://testnet1.wavesnodes.com/
```

so it deletes the last character.

**Comment by eoliveros** [comment]
PR created

**Comment by eoliveros** [comment]
pulling then deploying again

**Comment by eoliveros** [comment]
currently blank:
![image](https://user-images.githubusercontent.com/47799652/84720040-1004d800-afd1-11ea-9c76-5c48cc657019.png)


initialised:
![image](https://user-images.githubusercontent.com/47799652/84719922-b8666c80-afd0-11ea-80ab-4d317875d2a4.png)

trying after initialized:
![image](https://user-images.githubusercontent.com/47799652/84719961-d3d17780-afd0-11ea-92d5-0bbd36e4daf8.png)


Looks good.

**Comment by djpnewton** [comment]
cool
